"""initial migration

Revision ID: 94c88c494255
Revises: 
Create Date: 2026-06-04 14:03:33.551737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94c88c494255'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', name='user_role_enum'), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('hostels',
    sa.Column('hostel_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('hostel_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('area', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('contact_phone', sa.String(length=15), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'co-ed', name='hostel_gender_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('hostel_id')
    )
    with op.batch_alter_table('hostels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hostels_owner_id'), ['owner_id'], unique=False)

    op.create_table('hostel_images',
    sa.Column('image_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hostel_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostels.hostel_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('image_id')
    )
    with op.batch_alter_table('hostel_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hostel_images_hostel_id'), ['hostel_id'], unique=False)

    op.create_table('reviews',
    sa.Column('review_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hostel_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_name', sa.String(length=100), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name='rating_range_check'),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostels.hostel_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('review_id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_hostel_id'), ['hostel_id'], unique=False)

    op.create_table('rooms',
    sa.Column('room_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hostel_id', sa.Integer(), nullable=False),
    sa.Column('room_type', sa.Enum('single', 'double', 'triple', name='room_type_enum'), nullable=False),
    sa.Column('rent', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('available_beds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostels.hostel_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_id')
    )
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rooms_hostel_id'), ['hostel_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rooms_hostel_id'))

    op.drop_table('rooms')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_hostel_id'))

    op.drop_table('reviews')
    with op.batch_alter_table('hostel_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hostel_images_hostel_id'))

    op.drop_table('hostel_images')
    with op.batch_alter_table('hostels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hostels_owner_id'))

    op.drop_table('hostels')
    op.drop_table('users')
    # ### end Alembic commands ###
